/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DayLog = IDL.Record({ 'date' : IDL.Text, 'steps' : IDL.Int });

export const idlService = IDL.Service({
  'addSteps' : IDL.Func([IDL.Text, IDL.Int], [IDL.Int], []),
  'getLast7Days' : IDL.Func([IDL.Int], [IDL.Vec(DayLog)], ['query']),
  'getTodaySteps' : IDL.Func([IDL.Text], [IDL.Int], ['query']),
  'logSteps' : IDL.Func([IDL.Text, IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DayLog = IDL.Record({ 'date' : IDL.Text, 'steps' : IDL.Int });
  
  return IDL.Service({
    'addSteps' : IDL.Func([IDL.Text, IDL.Int], [IDL.Int], []),
    'getLast7Days' : IDL.Func([IDL.Int], [IDL.Vec(DayLog)], ['query']),
    'getTodaySteps' : IDL.Func([IDL.Text], [IDL.Int], ['query']),
    'logSteps' : IDL.Func([IDL.Text, IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };